name: watch_store
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/watches/
    - assets/svgs/
    - assets/svgs/home/
    - assets/svgs/watches/

  fonts:
    - family: raleway
      fonts:
        - asset: fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/raleway/Raleway-Black.ttf
          weight: 700
        - asset: fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/raleway/Raleway-Regular.ttf
          weight: 400
